/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 glasses.glb --transform --resolution 1024 
Files: glasses.glb [4.53MB] > C:\Users\Hamza Computers\Desktop\ObjectViewer\v2\ibtikarz-3d-viewer\public\glasses-transformed.glb [345.94KB] (92%)
Author: nazarchi091 (https://sketchfab.com/nazarchi091)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-glasses-8425ebedb9334fc3a1e6d7a72f5612b4
Title: Black Glasses
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glasses-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_10.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Handles} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Frame.1']} />
    </group>
  )
}

useGLTF.preload('/glasses-transformed.glb')
