/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ring.glb --transform --resolution 1024 
Files: ring.glb [13.62MB] > C:\Users\Hamza Computers\Desktop\ObjectViewer\v2\ibtikarz-3d-viewer\public\ring-transformed.glb [4.4MB] (68%)
Author: Busanello (https://sketchfab.com/busanello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-diamond-solitaire-engagement-ring-61e45adb7e4a4d0f9f9d6f1375dc8334
Title: Black Diamond Solitaire Engagement Ring
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ring-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Default} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Material_1} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ring-transformed.glb')
